apiVersion: v1
kind: Secret
metadata:
  name: mysql-cred
  namespace: wordpress
type: Opaque
data:
  admin-password: YWRtaW5AMTIz
  username: Y3J1bmNob3Bz
  password: Y3J1bmNob3BzQDEyMw==
  db-name: d29yZHByZXNzX2Ri